name: Run Shell Commands
on: [push]

jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      -name: Echo a String
       run: eaho "Hello ! this is my first hithub actions workflow file"